name: deeplightning
dependencies:
  - pip==21.2.4
  - python==3.8.2 # numpy==1.22 not working with python==3.9
  - pip:
    - colorama==0.4.4
    - deepspeed==0.5.10
    - einops==0.4.0
    - flask==2.0.3
    - mlflow==1.24
    - numpy==1.22.2
    - omegaconf==2.1.1
    - pandas==1.4.1
    - pyyaml==6.0
    - matplotlib==3.5.1
    - pytorch_lightning==1.5.10
    - torch==1.10.2
    - torchvision==0.11.3
    - wandb==0.12.21