name: deeplightning
channels:
  - defaults
  - conda-forge
dependencies:
  - pip==23.0.1
  - python==3.10 # numpy==1.22 not working with python==3.9
  - pip:
    - colorama==0.4.4
    - deepspeed==0.5.10
    - einops==0.4.0
    - flask==2.0.3
    - imagesize==1.4.1
    - ipython
    - librosa==0.9.2
    - lightning==2.0.0
    - matplotlib==3.5.1
    - numpy==1.23.5
    - omegaconf==2.1.1
    - opencv-python==4.7.0.72 #==4.1.2.30
    - pandas==1.5.3
    - pyyaml==6.0
    - seaborn==0.12.0
    - torch==2.0.0 #==1.13.1
    - torchaudio==2.0.1
    - torchlibrosa==0.1.0
    - torchmetrics==0.11.4 #0.11.0
    - torchvision==0.15.1  #0.11.3
    - wandb==0.12.21