task: classification
data:
  root: /Users/pme12/data/
  dataset: MNIST
  num_workers: 4
  batch_size: 256
  module:
    target: tests.helpers.dummies.DummyDataset
    params:
      length: 5
      size: 8

model:
  module:
    target: tests.helpers.dummies.DummyModel
  network:
    type: null
    params: 
      num_classes: 10
      num_channels: 1
  optimizer:
    target: torch.optim.SGD
    params:
      lr: 0.01
      weight_decay: 0.01
      momentum: 0.9
  scheduler:
    target: torch.optim.lr_scheduler.ExponentialLR
    params:
      gamma: 0.99
    call:
      interval: "epoch"
      frequency: 1
  loss:
    target: torch.nn.CrossEntropyLoss
    params:

engine:
  accelerator: cpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32

metrics:
  train: default
  val: default
  test: default

train:
  num_epochs: 1
  val_every_n_epoch: 1
  grad_accum_from_epoch: 0
  grad_accum_every_n_batches: 1
  ckpt_resume_path: null
  ckpt_monitor_metric: null  # used in `ModelCheckpoint` callback
  ckpt_every_n_epochs: 1
  ckpt_save_top_k: 1
  early_stop_metric: null
  early_stop_delta: 0.001
  early_stop_patience: 3

logger:
  name: wandb
  project_name: unittests
  tags: ["_"] # cannot be empty
  notes: null
  log_every_n_steps: 20