task: reconstruction
data:
  root: /Users/pme12/data/
  dataset: MNIST
  resize: 32 # VQVAE requires image size to be power of 2
  num_workers: 4
  batch_size: 128
  module:
    target: deeplightning.data.dataloaders.mnist.MNIST

model:
  module:
    target: deeplightning.task.image.reconstructionVAE.ImageReconstructionVAE
  network:
    target: deeplightning.models.vqvae.DiscreteVAE
    params: 
      image_size: 32
      num_tokens: 8 #512
      codebook_dim: 32 #256
      num_layers: 1 #2
      num_resnet_blocks: 1 #2
      hidden_dim: 32 #128
      channels: 1
      temperature: 0.9
      straight_through: False
      kl_div_loss_weight: 0.0
      normalization: null
  optimizer:
    target: torch.optim.Adadelta
    params:
  scheduler:
    target: torch.optim.lr_scheduler.ExponentialLR
    params:
      gamma: 0.99
    call:
      interval: "epoch"
      frequency: 1
  loss:
    target: deeplightning.modules.loss.vqvae_loss.VQVAE_Loss
    params:
      smooth_l1_loss: True
      num_tokens: ${model.network.params.num_tokens}
      kl_div_loss_weight: ${model.network.params.kl_div_loss_weight}
  
engine:
  backend: deepspeed_stage_3
  gpus: null
  num_nodes: 1
  precision: 32

train:
  num_epochs: 10
  val_every_n_epoch: 1
  grad_accum_from_epoch: 0
  grad_accum_every_n_batches: 1
  ckpt_resume_path: null
  ckpt_every_n_epochs: 1
  early_stop_metric: null
  early_stop_delta: 0.001
  early_stop_patience: 3

logger:
log_to_wandb: true
project_name: trial
tags: ["image", "reconstruction", "vqvae"] # cannot be empty
notes: null
  type: pytorch_lightning.loggers.MLFlowLogger
  params:
    experiment_name: Default
    tracking_uri: mlruns
  log_every_n_steps: 10