modes: 
  train: true
  test: true
  
task: classification

data:
  root: /Users/pme/data/MNIST
  num_workers: 4
  batch_size: 256
  module: 
    target: deeplightning.data.mnist.MNIST
  image_size: 28
  num_channels: 1
  num_classes: 10

model:
  module: 
    target: deeplightning.task.image.classification.ImageClassification
  network:
    target: deeplightning.model.mlpmixer.MLPMixer
    params: 
      image_size: ${data.image_size}
      num_channels: ${data.num_channels}
      num_classes: ${data.num_classes}
      patch_size: 4
      dim: 512
      depth: 6 #12
  optimizer:
    target: torch.optim.Adadelta
    params:
  scheduler:
    target: torch.optim.lr_scheduler.ExponentialLR
    params:
      gamma: 0.99
    call:
      interval: "epoch"
      frequency: 1
  loss:
    target: torch.nn.CrossEntropyLoss
    params:

engine:
  backend: deepspeed_stage_3
  gpus: null
  num_nodes: 1
  precision: 32

train:
  num_epochs: 2
  val_every_n_epoch: 1
  grad_accum_from_epoch: 0
  grad_accum_every_n_batches: 1
  ckpt_resume_path: null
  ckpt_every_n_epochs: 1
  early_stop_metric: null
  early_stop_delta: 0.001
  early_stop_patience: 3

logger:
  log_to_wandb: true
  project_name: trial
  tags: ["image", "classification", "resnet"] # cannot be empty
  notes: null
  log_every_n_steps: 10
  type: pytorch_lightning.loggers.MLFlowLogger
  params:
    experiment_name: Default
    tracking_uri: mlruns