task: detection
model_cfg: "external/yolov5/models/yolov5x.yaml"
model_ckpt: "/Users/pme/code/yolov5/yolov5x6.pt"
input_path: "/Users/pme/Downloads/people.jpeg"
save_path: "/Users/pme/Downloads/tests/"

engine:
  backend: null
  gpus: null
  num_nodes: 1